Implement Euclid division and remainder
rust-num/num-bigint pull request #245
Opened 2022-07-16 20:11 UTC by jaybosamiya

Now that a common trait for this has been sorted out (https://github.com/rust-num/num-traits/issues/159 implemented and merged in https://github.com/rust-num/num-traits/pull/195), we can now close https://github.com/rust-num/num-bigint/issues/146 by implementing the trait for `BigInt`s. This commit does just that.

2023-02-11 01:31 UTC, cuviper requested changes
Hi, and sorry for review silence.

For completeness, can you also add the trivial implementations for `BigUint`?

2023-02-11 01:31 UTC, cuviper commented on src/bigint/division.rs
> +        if self % v < BigInt::zero() {
This should use `div_rem` so we don't have to divide twice.

Also, `is_negative()` and `is_positive()` would be more direct than all the comparisons to `zero()`.

2023-03-31 20:45 UTC, jaybosamiya commented
Thanks for the review! I've added commits based on the above requested changes, and the branch is now ready for another review.

2023-08-22 20:41 UTC, cuviper commented
I rebased this and added a couple compat fixes. Otherwise, looks good, thanks!

bors r+

2023-08-22 20:59 UTC, cuviper commented
bors retry

2023-08-22 21:07 UTC, merged

2023-08-23 20:42 UTC, jaybosamiya commented
Thanks for rebasing and merging!